name: Node.js CI

on:
  issues:
    types: [opened, created, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testing action
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm init -y
