name: Node.js CI

on:
  issues:
    types: [opened, created, deleted]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Running npm
      run: npm init -y
    - name: Pushing back
      run: |
        git add .
        git commit -m "Add changes from Github Action" -a
        git push
